# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
username: "braian777" # < TU_USUARIO@hodl.ar

# NOSTR Settings
nostr: # Sin el # adelante
  npub: "npub16egmpnzjlc2ssxfxdltza7meu0u9j9smx07q2jaf3ep4xlj2jcqsma2vyk" # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Braian Alvez # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: Braian Alvez # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/braiancmo/
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
