# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

 #HODL username
 username: "braianalvez" # < braianalvez@hodl.ar

 # NOSTR Settings
 # nostr: # Sin el # adelante
   # npub: "npub16egmpnzjlc2ssxfxdltza7meu0u9j9smx07q2jaf3ep4xlj2jcqsma2vyk" # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Braian Alvez # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: Braian Alvez # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/braiancmo/

# - title: Twitter
 #  icon: twitter
  # url: https://twitter.com/braian_javierA
    
 #title: LinkedIn # Este es el nombre del botón
 # icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
  # url: https://www.linkedin.com/in/braian-javier-alvez-de-olivera-8a7b7850/ # Link a donde redireccionará al hacer click

 # title: Github
  # icon: github
  # url: https://github.com/Braianalvez

 #- title: Sitio Web
  # icon: url
   #url: https://marea.pro/braiancmo

 #- title: Telegram
  # icon: telegram
   #url: https://t.me/BJAlvez
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
